export default {
  countries: [ 
    {name: 'Afghanistan', value: 'AF'}, 
    {name: 'Åland Islands', value: 'AX'}, 
    {name: 'Albania', value: 'AL'}, 
    {name: 'Algeria', value: 'DZ'}, 
    {name: 'American Samoa', value: 'AS'}, 
    {name: 'AndorrA', value: 'AD'}, 
    {name: 'Angola', value: 'AO'}, 
    {name: 'Anguilla', value: 'AI'}, 
    {name: 'Antarctica', value: 'AQ'}, 
    {name: 'Antigua and Barbuda', value: 'AG'}, 
    {name: 'Argentina', value: 'AR'}, 
    {name: 'Armenia', value: 'AM'}, 
    {name: 'Aruba', value: 'AW'}, 
    {name: 'Australia', value: 'AU'}, 
    {name: 'Austria', value: 'AT'}, 
    {name: 'Azerbaijan', value: 'AZ'}, 
    {name: 'Bahamas', value: 'BS'}, 
    {name: 'Bahrain', value: 'BH'}, 
    {name: 'Bangladesh', value: 'BD'}, 
    {name: 'Barbados', value: 'BB'}, 
    {name: 'Belarus', value: 'BY'}, 
    {name: 'Belgium', value: 'BE'}, 
    {name: 'Belize', value: 'BZ'}, 
    {name: 'Benin', value: 'BJ'}, 
    {name: 'Bermuda', value: 'BM'}, 
    {name: 'Bhutan', value: 'BT'}, 
    {name: 'Bolivia', value: 'BO'}, 
    {name: 'Bosnia and Herzegovina', value: 'BA'}, 
    {name: 'Botswana', value: 'BW'}, 
    {name: 'Bouvet Island', value: 'BV'}, 
    {name: 'Brazil', value: 'BR'}, 
    {name: 'British Indian Ocean Territory', value: 'IO'}, 
    {name: 'Brunei Darussalam', value: 'BN'}, 
    {name: 'Bulgaria', value: 'BG'}, 
    {name: 'Burkina Faso', value: 'BF'}, 
    {name: 'Burundi', value: 'BI'}, 
    {name: 'Cambodia', value: 'KH'}, 
    {name: 'Cameroon', value: 'CM'}, 
    {name: 'Canada', value: 'CA'}, 
    {name: 'Cape Verde', value: 'CV'}, 
    {name: 'Cayman Islands', value: 'KY'}, 
    {name: 'Central African Republic', value: 'CF'}, 
    {name: 'Chad', value: 'TD'}, 
    {name: 'Chile', value: 'CL'}, 
    {name: 'China', value: 'CN'}, 
    {name: 'Christmas Island', value: 'CX'}, 
    {name: 'Cocos (Keeling) Islands', value: 'CC'}, 
    {name: 'Colombia', value: 'CO'}, 
    {name: 'Comoros', value: 'KM'}, 
    {name: 'Congo', value: 'CG'}, 
    {name: 'Congo, The Democratic Republic of the', value: 'CD'}, 
    {name: 'Cook Islands', value: 'CK'}, 
    {name: 'Costa Rica', value: 'CR'}, 
    {name: 'Cote D\'Ivoire', value: 'CI'}, 
    {name: 'Croatia', value: 'HR'}, 
    {name: 'Cuba', value: 'CU'}, 
    {name: 'Cyprus', value: 'CY'}, 
    {name: 'Czech Republic', value: 'CZ'}, 
    {name: 'Denmark', value: 'DK'}, 
    {name: 'Djibouti', value: 'DJ'}, 
    {name: 'Dominica', value: 'DM'}, 
    {name: 'Dominican Republic', value: 'DO'}, 
    {name: 'Ecuador', value: 'EC'}, 
    {name: 'Egypt', value: 'EG'}, 
    {name: 'El Salvador', value: 'SV'}, 
    {name: 'Equatorial Guinea', value: 'GQ'}, 
    {name: 'Eritrea', value: 'ER'}, 
    {name: 'Estonia', value: 'EE'}, 
    {name: 'Ethiopia', value: 'ET'}, 
    {name: 'Falkland Islands (Malvinas)', value: 'FK'}, 
    {name: 'Faroe Islands', value: 'FO'}, 
    {name: 'Fiji', value: 'FJ'}, 
    {name: 'Finland', value: 'FI'}, 
    {name: 'France', value: 'FR'}, 
    {name: 'French Guiana', value: 'GF'}, 
    {name: 'French Polynesia', value: 'PF'}, 
    {name: 'French Southern Territories', value: 'TF'}, 
    {name: 'Gabon', value: 'GA'}, 
    {name: 'Gambia', value: 'GM'}, 
    {name: 'Georgia', value: 'GE'}, 
    {name: 'Germany', value: 'DE'}, 
    {name: 'Ghana', value: 'GH'}, 
    {name: 'Gibraltar', value: 'GI'}, 
    {name: 'Greece', value: 'GR'}, 
    {name: 'Greenland', value: 'GL'}, 
    {name: 'Grenada', value: 'GD'}, 
    {name: 'Guadeloupe', value: 'GP'}, 
    {name: 'Guam', value: 'GU'}, 
    {name: 'Guatemala', value: 'GT'}, 
    {name: 'Guernsey', value: 'GG'}, 
    {name: 'Guinea', value: 'GN'}, 
    {name: 'Guinea-Bissau', value: 'GW'}, 
    {name: 'Guyana', value: 'GY'}, 
    {name: 'Haiti', value: 'HT'}, 
    {name: 'Heard Island and Mcdonald Islands', value: 'HM'}, 
    {name: 'Holy See (Vatican City State)', value: 'VA'}, 
    {name: 'Honduras', value: 'HN'}, 
    {name: 'Hong Kong', value: 'HK'}, 
    {name: 'Hungary', value: 'HU'}, 
    {name: 'Iceland', value: 'IS'}, 
    {name: 'India', value: 'IN'}, 
    {name: 'Indonesia', value: 'ID'}, 
    {name: 'Iran, Islamic Republic Of', value: 'IR'}, 
    {name: 'Iraq', value: 'IQ'}, 
    {name: 'Ireland', value: 'IE'}, 
    {name: 'Isle of Man', value: 'IM'}, 
    {name: 'Israel', value: 'IL'}, 
    {name: 'Italy', value: 'IT'}, 
    {name: 'Jamaica', value: 'JM'}, 
    {name: 'Japan', value: 'JP'}, 
    {name: 'Jersey', value: 'JE'}, 
    {name: 'Jordan', value: 'JO'}, 
    {name: 'Kazakhstan', value: 'KZ'}, 
    {name: 'Kenya', value: 'KE'}, 
    {name: 'Kiribati', value: 'KI'}, 
    {name: 'Korea, Democratic People\'S Republic of', value: 'KP'}, 
    {name: 'Korea, Republic of', value: 'KR'}, 
    {name: 'Kuwait', value: 'KW'}, 
    {name: 'Kyrgyzstan', value: 'KG'}, 
    {name: 'Lao People\'S Democratic Republic', value: 'LA'}, 
    {name: 'Latvia', value: 'LV'}, 
    {name: 'Lebanon', value: 'LB'}, 
    {name: 'Lesotho', value: 'LS'}, 
    {name: 'Liberia', value: 'LR'}, 
    {name: 'Libyan Arab Jamahiriya', value: 'LY'}, 
    {name: 'Liechtenstein', value: 'LI'}, 
    {name: 'Lithuania', value: 'LT'}, 
    {name: 'Luxembourg', value: 'LU'}, 
    {name: 'Macao', value: 'MO'}, 
    {name: 'Macedonia, The Former Yugoslav Republic of', value: 'MK'}, 
    {name: 'Madagascar', value: 'MG'}, 
    {name: 'Malawi', value: 'MW'}, 
    {name: 'Malaysia', value: 'MY'}, 
    {name: 'Maldives', value: 'MV'}, 
    {name: 'Mali', value: 'ML'}, 
    {name: 'Malta', value: 'MT'}, 
    {name: 'Marshall Islands', value: 'MH'}, 
    {name: 'Martinique', value: 'MQ'}, 
    {name: 'Mauritania', value: 'MR'}, 
    {name: 'Mauritius', value: 'MU'}, 
    {name: 'Mayotte', value: 'YT'}, 
    {name: 'Mexico', value: 'MX'}, 
    {name: 'Micronesia, Federated States of', value: 'FM'}, 
    {name: 'Moldova, Republic of', value: 'MD'}, 
    {name: 'Monaco', value: 'MC'}, 
    {name: 'Mongolia', value: 'MN'}, 
    {name: 'Montserrat', value: 'MS'}, 
    {name: 'Morocco', value: 'MA'}, 
    {name: 'Mozambique', value: 'MZ'}, 
    {name: 'Myanmar', value: 'MM'}, 
    {name: 'Namibia', value: 'NA'}, 
    {name: 'Nauru', value: 'NR'}, 
    {name: 'Nepal', value: 'NP'}, 
    {name: 'Netherlands', value: 'NL'}, 
    {name: 'Netherlands Antilles', value: 'AN'}, 
    {name: 'New Caledonia', value: 'NC'}, 
    {name: 'New Zealand', value: 'NZ'}, 
    {name: 'Nicaragua', value: 'NI'}, 
    {name: 'Niger', value: 'NE'}, 
    {name: 'Nigeria', value: 'NG'}, 
    {name: 'Niue', value: 'NU'}, 
    {name: 'Norfolk Island', value: 'NF'}, 
    {name: 'Northern Mariana Islands', value: 'MP'}, 
    {name: 'Norway', value: 'NO'}, 
    {name: 'Oman', value: 'OM'}, 
    {name: 'Pakistan', value: 'PK'}, 
    {name: 'Palau', value: 'PW'}, 
    {name: 'Palestinian Territory, Occupied', value: 'PS'}, 
    {name: 'Panama', value: 'PA'}, 
    {name: 'Papua New Guinea', value: 'PG'}, 
    {name: 'Paraguay', value: 'PY'}, 
    {name: 'Peru', value: 'PE'}, 
    {name: 'Philippines', value: 'PH'}, 
    {name: 'Pitcairn', value: 'PN'}, 
    {name: 'Poland', value: 'PL'}, 
    {name: 'Portugal', value: 'PT'}, 
    {name: 'Puerto Rico', value: 'PR'}, 
    {name: 'Qatar', value: 'QA'}, 
    {name: 'Reunion', value: 'RE'}, 
    {name: 'Romania', value: 'RO'}, 
    {name: 'Russian Federation', value: 'RU'}, 
    {name: 'RWANDA', value: 'RW'}, 
    {name: 'Saint Helena', value: 'SH'}, 
    {name: 'Saint Kitts and Nevis', value: 'KN'}, 
    {name: 'Saint Lucia', value: 'LC'}, 
    {name: 'Saint Pierre and Miquelon', value: 'PM'}, 
    {name: 'Saint Vincent and the Grenadines', value: 'VC'}, 
    {name: 'Samoa', value: 'WS'}, 
    {name: 'San Marino', value: 'SM'}, 
    {name: 'Sao Tome and Principe', value: 'ST'}, 
    {name: 'Saudi Arabia', value: 'SA'}, 
    {name: 'Senegal', value: 'SN'}, 
    {name: 'Serbia and Montenegro', value: 'CS'}, 
    {name: 'Seychelles', value: 'SC'}, 
    {name: 'Sierra Leone', value: 'SL'}, 
    {name: 'Singapore', value: 'SG'}, 
    {name: 'Slovakia', value: 'SK'}, 
    {name: 'Slovenia', value: 'SI'}, 
    {name: 'Solomon Islands', value: 'SB'}, 
    {name: 'Somalia', value: 'SO'}, 
    {name: 'South Africa', value: 'ZA'}, 
    {name: 'South Georgia and the South Sandwich Islands', value: 'GS'}, 
    {name: 'Spain', value: 'ES'}, 
    {name: 'Sri Lanka', value: 'LK'}, 
    {name: 'Sudan', value: 'SD'}, 
    {name: 'Suriname', value: 'SR'}, 
    {name: 'Svalbard and Jan Mayen', value: 'SJ'}, 
    {name: 'Swaziland', value: 'SZ'}, 
    {name: 'Sweden', value: 'SE'}, 
    {name: 'Switzerland', value: 'CH'}, 
    {name: 'Syrian Arab Republic', value: 'SY'}, 
    {name: 'Taiwan, Province of China', value: 'TW'}, 
    {name: 'Tajikistan', value: 'TJ'}, 
    {name: 'Tanzania, United Republic of', value: 'TZ'}, 
    {name: 'Thailand', value: 'TH'}, 
    {name: 'Timor-Leste', value: 'TL'}, 
    {name: 'Togo', value: 'TG'}, 
    {name: 'Tokelau', value: 'TK'}, 
    {name: 'Tonga', value: 'TO'}, 
    {name: 'Trinidad and Tobago', value: 'TT'}, 
    {name: 'Tunisia', value: 'TN'}, 
    {name: 'Turkey', value: 'TR'}, 
    {name: 'Turkmenistan', value: 'TM'}, 
    {name: 'Turks and Caicos Islands', value: 'TC'}, 
    {name: 'Tuvalu', value: 'TV'}, 
    {name: 'Uganda', value: 'UG'}, 
    {name: 'Ukraine', value: 'UA'}, 
    {name: 'United Arab Emirates', value: 'AE'}, 
    {name: 'United Kingdom', value: 'GB'}, 
    {name: 'United States', value: 'US'}, 
    {name: 'United States Minor Outlying Islands', value: 'UM'}, 
    {name: 'Uruguay', value: 'UY'}, 
    {name: 'Uzbekistan', value: 'UZ'}, 
    {name: 'Vanuatu', value: 'VU'}, 
    {name: 'Venezuela', value: 'VE'}, 
    {name: 'Viet Nam', value: 'VN'}, 
    {name: 'Virgin Islands, British', value: 'VG'}, 
    {name: 'Virgin Islands, U.S.', value: 'VI'}, 
    {name: 'Wallis and Futuna', value: 'WF'}, 
    {name: 'Western Sahara', value: 'EH'}, 
    {name: 'Yemen', value: 'YE'}, 
    {name: 'Zambia', value: 'ZM'}, 
    {name: 'Zimbabwe', value: 'ZW'} 
  ],
  timezoneList: [
    { name: "(GMT-06:00) Guadalajara", value: "America/Mexico_City" },
    { name: "(GMT-06:00) Mexico City", value: "America/Mexico_City" },
    { name: "(GMT-06:00) Monterrey", value: "America/Monterrey" },
    { name: "(GMT-06:00) Saskatchewan", value: "America/Regina" },
    { name: "(GMT-05:00) Bogota", value: "America/Bogota" },
    {
      name: "(GMT-05:00) Eastern Time (US & Canada)",
      value: "America/New_York"
    },
    {
      name: "(GMT-05:00) Indiana (East)",
      value: "America/Indiana/Indianapolis"
    },
    { name: "(GMT-05:00) Lima", value: "America/Lima" },
    { name: "(GMT-05:00) Quito", value: "America/Lima" },
    { name: "(GMT-04:00) Atlantic Time (Canada)", value: "America/Halifax" },
    { name: "(GMT-04:00) Caracas", value: "America/Caracas" },
    { name: "(GMT-04:00) Georgetown", value: "America/Guyana" },
    { name: "(GMT-04:00) La Paz", value: "America/La_Paz" },
    { name: "(GMT-04:00) Puerto Rico", value: "America/Puerto_Rico" },
    { name: "(GMT-04:00) Santiago", value: "America/Santiago" },
    { name: "(GMT-03:00) Brasilia", value: "America/Sao_Paulo" },
    {
      name: "(GMT-03:00) Buenos Aires",
      value: "America/Argentina/Buenos_Aires"
    },
    { name: "(GMT-03:00) Greenland", value: "America/Godthab" },
    { name: "(GMT-03:00) Montevideo", value: "America/Montevideo" },
    { name: "(GMT-02:00) Mid-Atlantic", value: "Atlantic/South_Georgia" },
    { name: "(GMT-01:00) Azores", value: "Atlantic/Azores" },
    { name: "(GMT-01:00) Cape Verde Is.", value: "Atlantic/Cape_Verde" },
    { name: "(GMT+00:00) Edinburgh", value: "Europe/London" },
    { name: "(GMT+00:00) Lisbon", value: "Europe/Lisbon" },
    { name: "(GMT+00:00) London", value: "Europe/London" },
    { name: "(GMT+00:00) Monrovia", value: "Africa/Monrovia" },
    { name: "(GMT+00:00) UTC", value: "Etc/UTC" },
    { name: "(GMT+01:00) Amsterdam", value: "Europe/Amsterdam" },
    { name: "(GMT+01:00) Belgrade", value: "Europe/Belgrade" },
    { name: "(GMT+01:00) Berlin", value: "Europe/Berlin" },
    { name: "(GMT+01:00) Bern", value: "Europe/Zurich" },
    { name: "(GMT+01:00) Bratislava", value: "Europe/Bratislava" },
    { name: "(GMT+01:00) Brussels", value: "Europe/Brussels" },
    { name: "(GMT+01:00) Budapest", value: "Europe/Budapest" },
    { name: "(GMT+01:00) Casablanca", value: "Africa/Casablanca" },
    { name: "(GMT+01:00) Copenhagen", value: "Europe/Copenhagen" },
    { name: "(GMT+01:00) Dublin", value: "Europe/Dublin" },
    { name: "(GMT+01:00) Ljubljana", value: "Europe/Ljubljana" },
    { name: "(GMT+01:00) Madrid", value: "Europe/Madrid" },
    { name: "(GMT+01:00) Paris", value: "Europe/Paris" },
    { name: "(GMT+01:00) Prague", value: "Europe/Prague" },
    { name: "(GMT+01:00) Rome", value: "Europe/Rome" },
    { name: "(GMT+01:00) Sarajevo", value: "Europe/Sarajevo" },
    { name: "(GMT+01:00) Skopje", value: "Europe/Skopje" },
    { name: "(GMT+01:00) Stockholm", value: "Europe/Stockholm" },
    { name: "(GMT+01:00) Vienna", value: "Europe/Vienna" },
    { name: "(GMT+01:00) Warsaw", value: "Europe/Warsaw" },
    { name: "(GMT+01:00) West Central Africa", value: "Africa/Algiers" },
    { name: "(GMT+01:00) Zagreb", value: "Europe/Zagreb" },
    { name: "(GMT+01:00) Zurich", value: "Europe/Zurich" },
    { name: "(GMT+02:00) Athens", value: "Europe/Athens" },
    { name: "(GMT+02:00) Bucharest", value: "Europe/Bucharest" },
    { name: "(GMT+02:00) Cairo", value: "Africa/Cairo" },
    { name: "(GMT+02:00) Harare", value: "Africa/Harare" },
    { name: "(GMT+02:00) Helsinki", value: "Europe/Helsinki" },
    { name: "(GMT+02:00) Jerusalem", value: "Asia/Jerusalem" },
    { name: "(GMT+02:00) Kaliningrad", value: "Europe/Kaliningrad" },
    { name: "(GMT+02:00) Kyiv", value: "Europe/Kiev" },
    { name: "(GMT+02:00) Pretoria", value: "Africa/Johannesburg" },
    { name: "(GMT+02:00) Riga", value: "Europe/Riga" },
    { name: "(GMT+02:00) Sofia", value: "Europe/Sofia" },
    { name: "(GMT+02:00) Tallinn", value: "Europe/Tallinn" },
    { name: "(GMT+02:00) Vilnius", value: "Europe/Vilnius" },
    { name: "(GMT+03:00) Baghdad", value: "Asia/Baghdad" },
    { name: "(GMT+03:00) Istanbul", value: "Europe/Istanbul" },
    { name: "(GMT+03:00) Kuwait", value: "Asia/Kuwait" },
    { name: "(GMT+03:00) Minsk", value: "Europe/Minsk" },
    { name: "(GMT+03:00) Moscow", value: "Europe/Moscow" },
    { name: "(GMT+03:00) Nairobi", value: "Africa/Nairobi" },
    { name: "(GMT+03:00) Riyadh", value: "Asia/Riyadh" },
    { name: "(GMT+03:00) St. Petersburg", value: "Europe/Moscow" },
    { name: "(GMT+04:00) Abu Dhabi", value: "Asia/Muscat" },
    { name: "(GMT+04:00) Baku", value: "Asia/Baku" },
    { name: "(GMT+04:00) Muscat", value: "Asia/Muscat" },
    { name: "(GMT+04:00) Samara", value: "Europe/Samara" },
    { name: "(GMT+04:00) Tbilisi", value: "Asia/Tbilisi" },
    { name: "(GMT+04:00) Volgograd", value: "Europe/Volgograd" },
    { name: "(GMT+04:00) Yerevan", value: "Asia/Yerevan" },
    { name: "(GMT+05:00) Ekaterinburg", value: "Asia/Yekaterinburg" },
    { name: "(GMT+05:00) Islamabad", value: "Asia/Karachi" },
    { name: "(GMT+05:00) Karachi", value: "Asia/Karachi" },
    { name: "(GMT+05:00) Tashkent", value: "Asia/Tashkent" },
    { name: "(GMT+06:00) Almaty", value: "Asia/Almaty" },
    { name: "(GMT+06:00) Astana", value: "Asia/Dhaka" },
    { name: "(GMT+06:00) Dhaka", value: "Asia/Dhaka" },
    { name: "(GMT+06:00) Urumqi", value: "Asia/Urumqi" },
    { name: "(GMT+07:00) Bangkok", value: "Asia/Bangkok" },
    { name: "(GMT+07:00) Hanoi", value: "Asia/Bangkok" },
    { name: "(GMT+07:00) Jakarta", value: "Asia/Jakarta" },
    { name: "(GMT+07:00) Krasnoyarsk", value: "Asia/Krasnoyarsk" },
    { name: "(GMT+07:00) Novosibirsk", value: "Asia/Novosibirsk" },
    { name: "(GMT+08:00) Beijing", value: "Asia/Shanghai" },
    { name: "(GMT+08:00) Chongqing", value: "Asia/Chongqing" },
    { name: "(GMT+08:00) Hong Kong", value: "Asia/Hong_Kong" },
    { name: "(GMT+08:00) Irkutsk", value: "Asia/Irkutsk" },
    { name: "(GMT+08:00) Kuala Lumpur", value: "Asia/Kuala_Lumpur" },
    { name: "(GMT+08:00) Perth", value: "Australia/Perth" },
    { name: "(GMT+08:00) Singapore", value: "Asia/Singapore" },
    { name: "(GMT+08:00) Taipei", value: "Asia/Taipei" },
    { name: "(GMT+08:00) Ulaanbaatar", value: "Asia/Ulaanbaatar" },
    { name: "(GMT+09:00) Osaka", value: "Asia/Tokyo" },
    { name: "(GMT+09:00) Sapporo", value: "Asia/Tokyo" },
    { name: "(GMT+09:00) Seoul", value: "Asia/Seoul" },
    { name: "(GMT+09:00) Tokyo", value: "Asia/Tokyo" },
    { name: "(GMT+09:00) Yakutsk", value: "Asia/Yakutsk" },
    { name: "(GMT+10:00) Brisbane", value: "Australia/Brisbane" },
    { name: "(GMT+10:00) Canberra", value: "Australia/Melbourne" },
    { name: "(GMT+10:00) Guam", value: "Pacific/Guam" },
    { name: "(GMT+10:00) Hobart", value: "Australia/Hobart" },
    { name: "(GMT+10:00) Melbourne", value: "Australia/Melbourne" },
    { name: "(GMT+10:00) Port Moresby", value: "Pacific/Port_Moresby" },
    { name: "(GMT+10:00) Sydney", value: "Australia/Sydney" },
    { name: "(GMT+10:00) Vladivostok", value: "Asia/Vladivostok" },
    { name: "(GMT+11:00) Magadan", value: "Asia/Magadan" },
    { name: "(GMT+11:00) New Caledonia", value: "Pacific/Noumea" },
    { name: "(GMT+11:00) Solomon Is.", value: "Pacific/Guadalcanal" },
    { name: "(GMT+11:00) Srednekolymsk", value: "Asia/Srednekolymsk" },
    { name: "(GMT+12:00) Auckland", value: "Pacific/Auckland" },
    { name: "(GMT+12:00) Fiji", value: "Pacific/Fiji" },
    { name: "(GMT+12:00) Kamchatka", value: "Asia/Kamchatka" },
    { name: "(GMT+12:00) Marshall Is.", value: "Pacific/Majuro" },
    { name: "(GMT+12:00) Wellington", value: "Pacific/Auckland" },
    { name: "(GMT+13:00) Nuku'alofa", value: "Pacific/Tongatapu" },
    { name: "(GMT+13:00) Samoa", value: "Pacific/Apia" },
    { name: "(GMT+13:00) Tokelau Is.", value: "Pacific/Fakaofo" }
  ],
  days: [
    { id: 1, name: "Mo", value: "Monday", letter: "M" },
    { id: 2, name: "Tu", value: "Tuesday", letter: "T" },
    { id: 3, name: "We", value: "Wednesday", letter: "W" },
    { id: 4, name: "Th", value: "Thursday", letter: "T" },
    { id: 5, name: "Fr", value: "Friday", letter: "F" },
    { id: 6, name: "Sa", value: "Saturday", letter: "S" },
    { id: 7, name: "Su", value: "Sunday", letter: "S" }
  ]
}
